version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - liyasthomas
  labels:
  - Dependency upgrade
  ignore:
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: "@nuxtjs/pwa"
    versions:
    - 3.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
